import type { ConfirmedRoad } from "../road-detection/types";

export type RoadType =
  | "rural_undivided"
  | "rural_divided"
  | "urban_arterial"
  | "freeway";

export type Duration = "short" | "long";

export type ShoulderWorkType =
  | "utility_locate"
  | "survey"
  | "signal_cabinet"
  | "guardrail"
  | "other";

export type FlaggerWorkType =
  | "utility_cut"
  | "water_main"
  | "chip_seal"
  | "patching"
  | "other";

export type LaneClosureWorkType =
  | "pavement_repair"
  | "striping"
  | "drainage"
  | "bridge_deck"
  | "guardrail"
  | "other";

export type LaneClosureRoadType = "rural_divided" | "freeway";

export type WorkBeyondShoulderRoadType =
  | "rural_undivided"
  | "rural_divided"
  | "urban_arterial"
  | "freeway";

export type WorkBeyondShoulderWorkType =
  | "utility"
  | "environmental"
  | "landscaping"
  | "survey"
  | "fence_repair"
  | "other";

export type MobileRoadType2Lane = "rural_undivided" | "urban_arterial";
export type MobileRoadTypeMultilane = "rural_divided" | "freeway";

export type MobileWorkType =
  | "striping"
  | "sweeping"
  | "mowing"
  | "patching_pothole"
  | "crack_seal"
  | "sign_maintenance"
  | "asphalt_repair"
  | "other";

export type NearIntersectionRoadType = "rural_undivided" | "urban_arterial";

export type NearIntersectionWorkType =
  | "utility_cut"
  | "water_main"
  | "patching"
  | "signal_work"
  | "other";

/**
 * One cross-street leg entering the intersection. Field names match the
 * backend ``IntersectionApproach`` (src/api/schemas.py) exactly — the
 * scenario object IS the wire payload, there is no serializer between
 * them. UI-only state (the needs-confirmation treatment on detected
 * lane counts) must live in component state, never on this type.
 */
export interface NearIntersectionApproach {
  /** Generated by the form ("cross_a"/"cross_b"), never user-typed —
   *  keeps the backend's pattern/uniqueness/reserved-id 422s
   *  unrepresentable. */
  id: string;
  speed: number;
  roadType: NearIntersectionRoadType;
  /** Lanes per direction, same semantics as the mainline count. */
  lanesPerDirection: number;
  laneWidth: number;
  signalized: boolean;
  bearingDeg?: number;
  /**
   * Where the cross street's centerline crosses the mainline station
   * axis (0 = downstream end of the work zone, increasing upstream).
   * Negative = intersection past the work zone (near-side work);
   * greater than workLen = intersection before it (far-side work).
   * Both legs of the one cross street carry the same value.
   */
  alongStationFt: number;
  /**
   * Parsed OSM lane tags of the cross-street way, relayed from detection
   * (issue #120): raw total, forward, backward, and center-turn-lane
   * counts. Pure relays — the backend's lane-count consistency gate 400s
   * a near_intersection plan when total ≠ forward + backward + both_ways
   * (OSM data defect ⇒ the detected approach lane count can't be
   * trusted). Cleared when the operator confirms or edits the approach
   * lane count, which lifts the block. All undefined when OSM lacked the
   * tags — an absent relay never blocks.
   */
  detectedLanesTotal?: number;
  detectedLanesForward?: number;
  detectedLanesBackward?: number;
  detectedLanesBothWays?: number;
}

export interface NearIntersectionScenario extends JurisdictionPlanFields {
  kind: "near_intersection";
  meta: ScenarioMeta;

  roadType: NearIntersectionRoadType;
  speed: number;
  /** Per direction; the layout needs >= 2 (a 1-lane-per-direction road
   *  near an intersection is a flagger job, not this kind). */
  lanes: number;
  laneWidth: number;
  /** Always false in Phase 1 — the backend rejects divided mainlines.
   *  Kept on the wire because the schema requires the field. */
  divided: boolean;

  workType: NearIntersectionWorkType;
  duration: Duration;
  workLen: number;
  night: boolean;

  /** 1 leg (T-intersection) or 2 (both directions of one cross street). */
  approaches: NearIntersectionApproach[];
  /**
   * Override provenance (issue #177) — see `DetectionOverride`. Lives on
   * the scenario, not the approach: both legs carry the same way's tags,
   * so the erased detection is one fact, not one per leg.
   */
  detectionOverrides?: DetectionOverride[];
}

/**
 * Jurisdiction-layer extension (phase1-backend-spec §3.1) — additive,
 * all optional, snake_case (the scenario object IS the wire payload;
 * the backend's field names are snake_case by the spec's casing
 * decision §1.1 #1). Absent ⇒ baseline-only behavior, untouched.
 */
export interface JurisdictionPlanFields {
  jurisdiction_key?: string | null;
  street_class?: "local" | "collector" | "arterial" | null;
  schedule?: {
    date_mode: "single" | "range" | "tbd";
    work_date?: string;
    work_date_end?: string;
    start_time?: number;
    end_time?: number;
  } | null;
}

/**
 * A user confirm/edit that superseded a disputed detection (issue #177).
 * Mirrors `DetectionOverride` in src/api/schemas.py.
 *
 * The recovery affordances (#136/#158/#86 confirms, the #120 lane-edit
 * clears) lift a gate refusal or caution by erasing the detection
 * relays — which made a confirmed override byte-identical to a road
 * that was never detected. This marker preserves the disagreement:
 * only the relay fields that were actually present at erase time, plus
 * what the human asserted (the confirm's proposition, or the value the
 * user entered — never a fabricated number).
 *
 * Recorded ONLY for disputed erasures — the erased relays were driving
 * a live refusal or caution at that moment. An ordinary post-detection
 * lane edit with consistent relays is the established manual-supersede
 * convention (#112) and stays silent; absent detection records nothing,
 * ever. Informational only: the backend never re-blocks a confirmed
 * payload — the sole consumer is the audit's `detection_overridden`
 * item. No manual un-confirm exists (the rows are stateless and vanish
 * once the relay clears); re-running detection resets the list in the
 * same patch that re-attaches relays (applyClassification).
 */
export interface DetectionOverride {
  via:
    | "flagger_single_lane_confirm"
    | "flagger_multilane_confirm"
    | "flagger_twoway_confirm"
    | "shoulder_lane_edit"
    | "approach_lane_confirm"
    | "approach_lane_edit";
  detectedLanesTotal?: number;
  detectedLanesForward?: number;
  detectedLanesBackward?: number;
  detectedLanesBothWays?: number;
  detectedOneway?: string;
  asserted: string;
}

export type SiteConditionFlag =
  | "limited_sight_distance"
  | "adjacent_intersection"
  | "adjacent_interchange"
  | "driveways_present"
  | "pedestrian_facility"
  | "bicycle_facility"
  | "school_zone";

export type SiteConditions = Partial<Record<SiteConditionFlag, boolean>>;

export interface ScenarioMeta {
  project: string;
  address: string;
  /**
   * Site coordinates.  ``lat: 0, lng: 0`` is the UNSET sentinel (#186):
   * the type admits no null, every DEFAULT_* scenario starts at 0/0, and
   * literal 0/0 is never a legitimate site in scope.  Presence is asked
   * through ``hasLocation(meta)`` (lib/scenarios) — never re-derive it.
   */
  lat: number;
  lng: number;
  /**
   * Engineering-style location text shown on the title block (e.g.
   * "I-25 NB, MP 144.5–146, Colorado Springs"). Distinct from
   * ``address`` which is geocodable; ``locationDescription`` is human
   * prose for the LOCATION row of the schematic title block.
   */
  locationDescription?: string;
  /**
   * Road compass bearing (0 = N, 90 = E). Rotates the north arrow on
   * the rendered schematic to match the site. Leave undefined for the
   * default "↑ = North" orientation with a verify-bearing caveat.
   */
  bearingDeg?: number;
  siteConditions?: SiteConditions;
  /**
   * The road choice confirmed in the location picker, keyed to the pin
   * it was confirmed at (lib/road-detection/types.ts).  Persisted here —
   * not as picker-local UI state — so it survives picker close/reopen
   * and page reload; the reopened picker restores it without firing
   * detection.  Provenance metadata only: the Python backend ignores it
   * (extra meta keys are dropped by the Pydantic schema) and no plan
   * math reads it.
   */
  confirmedRoad?: ConfirmedRoad | null;
  /**
   * Road centerline as [lat, lng] vertices (#140) — a WIRE-ONLY field
   * materialized by ``withRelayedCenterline`` at serialization time
   * from ``confirmedRoad.candidate.geometry`` (behind the same exact
   * pinLat/pinLng staleness key the picker uses).  Never set on stored
   * scenario state; the backend reads it to draw the PDF corridor
   * along the road.  Absent ⇒ the straight-chord frame.
   */
  centerline?: Array<[number, number]>;
}

export interface ShoulderScenario extends JurisdictionPlanFields {
  kind: "shoulder";
  meta: ScenarioMeta;

  roadType: RoadType;
  speed: number;
  lanes: number;
  laneWidth: number;
  divided: boolean;

  workType: ShoulderWorkType;
  duration: Duration;
  workLen: number;
  night: boolean;
  /**
   * Reduced speed limit through the work zone, or undefined when no
   * reduction is in effect. Server rejects values > posted speed;
   * values equal to posted are normalized to "no reduction" at the
   * Python bridge. Operator-set only — never auto-applied from OSM
   * or work type. See V1-Wide Item 1 (CDOT S-630-1 Sheet 2, General Note 3).
   */
  workZoneSpeed?: number;
  /**
   * Raw OSM total-lane count relayed from detection (issue #136), before
   * the per-direction halving that fills ``lanes``. Pure relay — drives no
   * geometry or label; the backend's single-lane eligibility gate refuses
   * a genuinely single-lane undivided road (detectedLanesTotal === 1).
   * Cleared when the operator edits the lane count, which lifts the block.
   */
  detectedLanesTotal?: number;
  /**
   * Parsed OSM `lanes:forward` / `lanes:backward` / `lanes:both_ways`
   * counts relayed from detection (issue #120). Pure relays — no geometry
   * or label reads them; the backend audit emits a non-blocking "verify
   * lane count" caution when total ≠ forward + backward + both_ways.
   * Cleared alongside `detectedLanesTotal` when the operator edits the
   * lane count — an operator-owned count is no longer a detection claim.
   */
  detectedLanesForward?: number;
  detectedLanesBackward?: number;
  detectedLanesBothWays?: number;
  /** Override provenance (issue #177) — see `DetectionOverride`. */
  detectionOverrides?: DetectionOverride[];
}

export type FlaggerRoadType = "rural_undivided" | "urban_arterial";

export interface FlaggerLaneClosureScenario extends JurisdictionPlanFields {
  kind: "flagger_lane_closure";
  meta: ScenarioMeta;

  roadType: FlaggerRoadType;
  speed: number;
  laneWidth: number;

  workType: FlaggerWorkType;
  duration: Duration;
  workLen: number;
  night: boolean;

  pilotCar: boolean;
  afad: boolean;
  pedestrianAccess: boolean;
  /**
   * Raw OSM total-lane count relayed from detection (issue #136). A
   * flagger is always undivided (TA-10), so detectedLanesTotal === 1 is a
   * genuinely single-lane road, which the backend refuses. Cleared when
   * the operator confirms the road has a lane in each direction.
   */
  detectedLanesTotal?: number;
  /**
   * Raw OSM `oneway` tag value relayed from detection (issue #158). A
   * flagger (TA-10) alternates traffic between two opposing directions, so
   * a one-directional value (`yes`/`-1`/`reversible`) is refused by the
   * backend — there is no opposing direction to hold. `no`/undefined is
   * two-way and never blocks. Cleared when the operator confirms the road
   * carries two-way traffic.
   */
  oneway?: string;
  /**
   * Parsed OSM per-direction lane counts relayed from detection (issue
   * #120) — see the matching fields on ShoulderScenario. Non-blocking:
   * the flagger has no lane field to correct, so the audit caution is the
   * only consumer.
   */
  detectedLanesForward?: number;
  detectedLanesBackward?: number;
  detectedLanesBothWays?: number;
  /** Override provenance (issue #177) — see `DetectionOverride`. */
  detectionOverrides?: DetectionOverride[];
}

export interface LaneClosureDividedScenario extends JurisdictionPlanFields {
  kind: "lane_closure_divided";
  meta: ScenarioMeta;

  roadType: LaneClosureRoadType;
  speed: number;
  laneWidth: number;

  workType: LaneClosureWorkType;
  duration: Duration;
  workLen: number;
  night: boolean;

  truckMountedAttenuator: boolean;
}

export interface WorkBeyondShoulderScenario extends JurisdictionPlanFields {
  kind: "work_beyond_shoulder";
  meta: ScenarioMeta;

  roadType: WorkBeyondShoulderRoadType;
  speed: number;
  laneWidth: number;

  workType: WorkBeyondShoulderWorkType;
  duration: Duration;
  workLen: number;
  night: boolean;
}

export interface MobileOp2LaneScenario extends JurisdictionPlanFields {
  kind: "mobile_op_2lane";
  meta: ScenarioMeta;

  roadType: MobileRoadType2Lane;
  speed: number;
  laneWidth: number;

  workType: MobileWorkType;
  workLen: number; // trailing distance to shadow vehicle (ft)
  night: boolean;

  arrowBoardOnShadow: boolean;
}

export interface MobileOpMultilaneScenario extends JurisdictionPlanFields {
  kind: "mobile_op_multilane";
  meta: ScenarioMeta;

  roadType: MobileRoadTypeMultilane;
  speed: number;
  laneWidth: number;

  workType: MobileWorkType;
  workLen: number; // trailing distance to shadow vehicle (ft)
  night: boolean;

  secondTMA: boolean;
}

export type Scenario =
  | ShoulderScenario
  | FlaggerLaneClosureScenario
  | LaneClosureDividedScenario
  | WorkBeyondShoulderScenario
  | MobileOp2LaneScenario
  | MobileOpMultilaneScenario
  | NearIntersectionScenario;
export type ScenarioKind = Scenario["kind"];

interface ResultBase {
  ta: string;
  cdotSheet: string;
  caseId: string;

  L: number;
  B: number;
  spacing: number;

  taperCones: number;
  tangentCones: number;
  cones: number;
  drums: number;
  signs: number;
  arrowBoards: number;

  totalDevices: number;
  uniqueTypes: number;
  steps: number;
}

export interface ShoulderResult extends ResultBase {
  kind: "shoulder";
}

export interface FlaggerResult extends ResultBase {
  kind: "flagger_lane_closure";
  flaggerStations: number;
  pilotCarVehicles: number;
  afadDevices: number;
  sightDistance: number;
}

export interface LaneClosureResult extends ResultBase {
  kind: "lane_closure_divided";
  tmaCount: number;
}

export interface WorkBeyondShoulderResult extends ResultBase {
  kind: "work_beyond_shoulder";
}

export interface MobileOp2LaneResult extends ResultBase {
  kind: "mobile_op_2lane";
  shadowVehicles: number;
  tmaCount: number;
}

export interface MobileOpMultilaneResult extends ResultBase {
  kind: "mobile_op_multilane";
  shadowVehicles: number;
  tmaCount: number;
}

export interface NearIntersectionResult extends ResultBase {
  kind: "near_intersection";
  /** Cross-street legs carrying their own advance signing. */
  approachCount: number;
  signalizedApproaches: number;
}

export type ScenarioResult =
  | ShoulderResult
  | FlaggerResult
  | LaneClosureResult
  | WorkBeyondShoulderResult
  | MobileOp2LaneResult
  | MobileOpMultilaneResult
  | NearIntersectionResult;
