// Cross-language spacing parity (engine-removal, Decision 1).
//
// tests/fixtures/spacing_parity.json is generated by the Python source
// of truth (tests/test_spacing_parity_fixture.py, from
// src/rules/spacing.py).  This test runs the TS mirror over the same
// grid and asserts equality — a backend table change the mirror doesn't
// follow fails HERE; a stale fixture fails the pytest side.
//
// MIGRATION PROOF, not a permanent guard: this file, the fixture, and
// corridor-spacing.ts are all deleted together in PR D.  The fixture
// deliberately excludes roadCategory=null at >= 55 mph — the backend
// refuses to auto-infer there while this mirror silently guesses
// "rural"; that divergence is the unsafe behavior being retired, not
// parity to preserve.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildCorridorSpec,
  minWorkZoneFt,
  type AdvanceRoadCategory,
} from "@/lib/corridor-spacing";
import type { ScenarioKind } from "@/lib/scenarios";

interface ParityRow {
  kind: ScenarioKind;
  speedMph: number;
  laneWidthFt: number;
  shoulderWidthFt: number;
  roadCategory: AdvanceRoadCategory | null;
  taperFt: number;
  bufferFt: number;
  advanceWarningFt: number;
  minWorkZoneFt: number;
}

const FIXTURE = resolve(
  __dirname,
  "../../../tests/fixtures/spacing_parity.json",
);

describe("spacing parity — TS mirror vs src/rules/spacing.py golden grid", () => {
  const rows = JSON.parse(readFileSync(FIXTURE, "utf-8")) as ParityRow[];

  it("fixture is present and non-trivial", () => {
    expect(rows.length).toBeGreaterThan(300);
  });

  it("every grid row matches the Python values exactly", () => {
    const failures: string[] = [];
    for (const row of rows) {
      const spec = buildCorridorSpec({
        anchorLat: 0,
        anchorLng: 0,
        bearingDeg: 0,
        speedMph: row.speedMph,
        workZoneFt: 0,
        scenarioKind: row.kind,
        laneWidthFt: row.laneWidthFt,
        shoulderWidthFt: row.shoulderWidthFt,
        roadCategory: row.roadCategory,
      });
      const min = minWorkZoneFt(
        row.kind,
        row.speedMph,
        row.laneWidthFt,
        row.shoulderWidthFt,
      );
      const id = `${row.kind}@${row.speedMph}mph/${row.roadCategory ?? "null"}`;
      if (Math.abs(spec.taperFt - row.taperFt) > 1e-6)
        failures.push(`${id}: taper ${spec.taperFt} != ${row.taperFt}`);
      if (Math.abs(spec.bufferFt - row.bufferFt) > 1e-6)
        failures.push(`${id}: buffer ${spec.bufferFt} != ${row.bufferFt}`);
      if (Math.abs(spec.advanceWarningFt - row.advanceWarningFt) > 1e-6)
        failures.push(
          `${id}: advance ${spec.advanceWarningFt} != ${row.advanceWarningFt}`,
        );
      if (Math.abs(min - row.minWorkZoneFt) > 1e-6)
        failures.push(`${id}: minWZ ${min} != ${row.minWorkZoneFt}`);
    }
    expect(failures).toEqual([]);
  });
});
