"""#290 checkpoint (k) commit 4 — the fixtures' work-start twins.

Run from the repo root:
    python validation-artifacts/committed/issue-290-pin-work/convert/make_twins.py

Ruling 10: "Pre-change plans and fixtures open with side unset, marked
needs-you; never silently re-read.  Lookout Mountain re-records on the
centerline."  So the corridor_end fixtures are NOT rewritten: each keeps
meaning what it meant.  Each gains a TWIN, written here by a stated
conversion, that says the same plan in the work-start model:

* the pin moves to the PLAN's work start — station ``D + W`` along the
  recorded bearing from the recorded pin, with ``D`` the downstream taper
  the plan builds (the §6B.08 floor, #257) and ``W`` the work length;
* the direction of travel is the recorded bearing's reciprocal (the old
  corridor's bearing points toward the first sign, corridor.py:24-27);
* the side is ``right`` (the only side the layout builds).

Nothing is re-read: the twin is a new record with its own provenance, and
the original stays byte-identical.  The Lookout Mountain twin walks the
recorded centerline (arc length, #140), so its work start sits on the road.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, ".")
from src.rules.corridor import (  # noqa: E402
    _initial_bearing_deg,
    build_corridor,
    travel_bearing_at,
)

HEADINGS = {0.0: "N", 90.0: "E", 180.0: "S", 270.0: "W"}
PDF_DIR = Path("tests/fixtures/pdf_worst_case")
SCANNED = ("scanned-ok", "scanned-not-checked", "scanned-dismissed", "scanned-asserted")
# The Lakewood fixtures' plan: shoulder, 45 mph urban arterial -> urban_high
# (schemas._map_road_type), 1,000 ft of work.  Read from each fixture below;
# only the corridor's lengths need the mapped road type.
ROAD_TYPE = {"urban_arterial": lambda mph: "urban_high" if mph > 40 else "urban_low"}


def pdf_twin(name: str) -> dict:
    src = json.loads((PDF_DIR / f"{name}.json").read_text(encoding="utf-8"))
    sc = src["scenario"]
    meta = sc["meta"]
    bearing = float(meta["bearingDeg"])
    corridor = build_corridor(
        lat=meta["lat"],
        lng=meta["lng"],
        bearing_deg=bearing,
        speed_mph=int(sc["speed"]),
        work_zone_ft=float(sc["workLen"]),
        closure_type=sc["kind"],
        road_type=ROAD_TYPE[sc["roadType"]](int(sc["speed"])),
    )
    start = corridor.point_at_station_ft(corridor.downstream_taper_ft + corridor.work_zone_ft)
    travel = (bearing + 180.0) % 360.0
    if travel not in HEADINGS:
        raise SystemExit(f"{name}: direction {travel} is not a four-way heading")
    twin = json.loads(json.dumps(src))
    twin_meta = twin["scenario"]["meta"]
    twin_meta.pop("bearingDeg")
    twin_meta.update(
        {
            "lat": round(start[0], 9),
            "lng": round(start[1], 9),
            "pinModel": "work_start",
            "work": {"side": "right", "heading": HEADINGS[travel]},
        }
    )
    twin["_provenance"] = {
        **src["_provenance"],
        "twin_of": f"{name}.json",
        "conversion": (
            f"#290 (k) commit 4: pin moved to the plan's work start, station D + W = "
            f"{corridor.downstream_taper_ft:g} + {corridor.work_zone_ft:g} ft along the "
            f"recorded bearing {bearing:g}; direction of travel = its reciprocal, "
            f"{travel:g} = heading {HEADINGS[travel]}; side right.  Generated by "
            "validation-artifacts/committed/issue-290-pin-work/convert/make_twins.py."
        ),
    }
    return twin


def lookout_twin() -> dict:
    path = Path("tests/fixtures/centerline/lookout_mountain_road.json")
    data = json.loads(path.read_text(encoding="utf-8"))
    centerline = tuple((p[0], p[1]) for p in data["centerline"])
    params = {
        "speed_mph": 40,
        "work_zone_ft": 800.0,
        "closure_type": "shoulder",
        "road_type": "urban_high",
    }
    v1 = build_corridor(
        lat=data["anchor"][0],
        lng=data["anchor"][1],
        bearing_deg=data["bearing_deg"],
        centerline=centerline,
        **params,
    )
    station = v1.downstream_taper_ft + v1.work_zone_ft
    start = v1.point_at_station_ft(station)
    downstream = v1.point_at_station_ft(station - 1.0)
    traffic = _initial_bearing_deg(*start, *downstream)
    with_geom = travel_bearing_at(
        *start, centerline=centerline, travel="with_geometry", heading=None
    )
    delta = abs(((traffic - with_geom + 540.0) % 360.0) - 180.0)
    travel = "with_geometry" if delta <= 90.0 else "against_geometry"
    return {
        "_provenance": {
            "twin_of": "lookout_mountain_road.json",
            "conversion": (
                "#290 (k) commit 4, ruling 10's re-record on the centerline: the work start "
                f"walked {station:g} ft (D {v1.downstream_taper_ft:g} + W {v1.work_zone_ft:g}) "
                "along the recorded centerline from the recorded anchor; the travel choice is "
                "the one whose derived direction matches the old corridor's downstream "
                f"direction there ({traffic:.1f} deg).  Generated by validation-artifacts/"
                "committed/issue-290-pin-work/convert/make_twins.py."
            ),
            "params": params,
        },
        "work_start": [round(start[0], 9), round(start[1], 9)],
        "travel": travel,
        "centerline_from": "lookout_mountain_road.json",
    }


def main() -> None:
    for name in SCANNED:
        out = PDF_DIR / f"{name}-work-start.json"
        out.write_text(json.dumps(pdf_twin(name), indent=2) + "\n", encoding="utf-8")
        print("wrote", out)
    out = Path("tests/fixtures/centerline/lookout_mountain_road.work-start.json")
    out.write_text(json.dumps(lookout_twin(), indent=2) + "\n", encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
