// s2-arc18 live check — #224 phase 4, operator corrections of the scanned
// site conditions (dismiss with a reason / assert, disclosed everywhere,
// re-generated by the backend, undone byte-identically).
//
// Two modes, picked from BASE (the s2a16/s2a17 idiom):
//   prod   BASE=https://www.conestruct.com     → the deployed site; the
//          prologue quotes /healthz verbatim and GATES on healthz sha ==
//          origin/main.
//   local  BASE=http://localhost:3000           → `next dev` on the working
//          tree with MODAL_RENDER_URL pointed at a local uvicorn of the
//          same tree (HEALTHZ env, default http://127.0.0.1:8765/healthz).
// Every wire leg goes THROUGH the Next proxy routes (/api/render/*, body
// {scenario}); the browser legs drive the real /sandbox with Playwright.
// The served classifier line is computed by the repo's Python mirror
// (src/rendering/tier_ledger.py via the .venv) over the SERVED audit —
// the same function that prints the audit-PDF cover.
//
// Legs (every wire leg carries site_scan and, where named, the correction
// on meta.siteConditionOverrides; a refused scan is recorded verbatim and
// retried up to RETRIES times):
//   A  baseline scanned audit + breakdown at the Lakewood control: sidewalks
//      detected ⇒ R9-9 on the device list; no corrections on the wire.
//   B  DISMISS the sidewalk (fenced): the audit's correction is applied
//      with scan_detected true and ONE backend sentence; pedestrian_facility
//      leaves flags; the site_adjustments record no longer fires; the
//      pending item site_condition_overridden carries the sentence
//      verbatim; the breakdown has no R9-9; pending = A's + 1.
//   C  ASSERT a school zone: applied with scan_detected false; the
//      school_zone record fires (S1-1 on the breakdown); pending = A's + 1.
//   D  MOOT: assert the detected sidewalk ⇒ status moot, flags and records
//      as A's, no pending item, the sentence still disclosed (rule 10).
//   E  the honest 400: a dismiss without a reason ⇒ HTTP 400,
//      error site_condition_override_invalid, recovery.field named.
//   F  audit PDF over the dismissed plan: the Result cell names the
//      dismissal, the sentence is in the body, the cover "Plan status" line
//      equals the classifier over leg B's audit when the two requests share
//      their detected set and corridor outcome (else INFO — the arc-17
//      lesson).
//   G  plan sheet + crew narrative over the dismissed plan: the sheet's
//      CORRECTED BY OPERATOR line; the narrative's ## Site Conditions with
//      the sentence.
//   H  browser: pin at Lakewood, Generate; the strip shows "Site conditions
//      — scanned" with a Dismiss on the detected sidewalk row; Dismiss →
//      reason picker → fenced → Confirm ⇒ the next audit request carries
//      the marker; the plan re-generates; the row is the × record with the
//      backend sentence + Undo; the on-screen ledger equals the classifier
//      over the browser's own served (corrected) audit; section 03 shows
//      "dismissed by operator"; Undo ⇒ the next request's meta is
//      byte-identical to the pre-dismiss request's meta and the ledger
//      returns to its pre-dismiss line.
//   I  browser: Assert on the absent School zone row ⇒ ✓ record, section
//      03's changed row carries the sentence with tag OPERATOR; the #243
//      Note 8 false FAIL is expected on this divided road — recorded, not
//      judged; Undo.
//   J  browser: with a correction on the wire, move the pin (Edit full
//      setup → the location editor → a nudged latitude) ⇒ the next
//      request carries no siteConditionOverrides (INFO if the editor's
//      affordance is not reachable this way).
//   K  axe (wcag2a/aa/21aa/22aa) post-generate with the block open and
//      with a record showing ≤ the s2-arc11 prod baseline 2.
//   L  sizes; saved-plan reload is proven at test level (INFO).
//
// Usage: node s2a18-lc-prod.js [outDir]   (BASE, HEALTHZ, RETRIES env)

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { chromium } = require("playwright");

const BASE = (process.env.BASE || "https://www.conestruct.com").replace(/\/$/, "");
const PROD = /conestruct\.com/.test(BASE);
const HEALTHZ_PROD = "https://rtmakatura--conestruct-render-fastapi-app.modal.run/healthz";
const HEALTHZ = PROD ? HEALTHZ_PROD : process.env.HEALTHZ || "http://127.0.0.1:8765/healthz";
// Absolute: the Python classifier is invoked with cwd = the repo root.
const OUT = path.resolve(process.argv[2] || (PROD ? "outS2A18Prod" : "outS2A18Local"));
const RETRIES = Number(process.env.RETRIES || 3);
// ONLY_J=1: the gate, then the browser pin → Generate → Assert → the pin-move
// leg (J) → axe, nothing else — the fix-224-manual-pin-move re-check.
const ONLY_J = process.env.ONLY_J === "1";
const REPO = execSync("git rev-parse --show-toplevel").toString().trim();
const PY = path.join(REPO, ".venv", "Scripts", "python.exe");
const AXE_SRC = fs.readFileSync(require.resolve("axe-core/axe.min.js"), "utf-8");

const LAT = "39.711300", LNG = "-105.081500", BEARING = "180", WORKLEN = "1000";
const CODE_SCAN = "site_scan_unavailable";
const CODE_OVERRIDE = "site_condition_override_invalid";
const AXE_BASELINE = 2;
const AT = "2026-09-04T12:00:00+00:00";
const DISMISS_SIDEWALK = { flag: "pedestrian_facility", action: "dismiss", reason: "fenced", recorded_at: AT };
const ASSERT_SCHOOL = { flag: "school_zone", action: "assert", recorded_at: AT };
const ASSERT_SIDEWALK = { flag: "pedestrian_facility", action: "assert", recorded_at: AT };

const lines = [];
let pass = 0, fail = 0, info = 0;
const log = (s) => { lines.push(s); console.log(s); };
const ok = (cond, name, detail) => {
  if (cond) { pass++; log(`**PASS** — ${name}${detail ? " — " + detail : ""}`); }
  else { fail++; log(`**FAIL** — ${name}${detail ? " — " + detail : ""}`); }
  return cond;
};
const note = (name, detail) => { info++; log(`INFO — ${name}${detail ? " — " + detail : ""}`); };
const save = (name, data) => fs.writeFileSync(path.join(OUT, name), data);
const finish = (code) => { save("s2a18-lc.md", lines.join("\n") + "\n"); process.exit(code); };

function scenario(over = {}, overrides = null) {
  const meta = { project: "s2a18 live check", address: "", lat: Number(LAT), lng: Number(LNG), bearingDeg: Number(BEARING) };
  if (overrides) meta.siteConditionOverrides = overrides;
  return {
    kind: "shoulder", meta,
    roadType: "urban_arterial", speed: 45, lanes: 2, laneWidth: 12, divided: true,
    workType: "utility_locate", duration: "short", workLen: Number(WORKLEN), night: false,
    site_scan: { proceed_if_unavailable: false },
    ...over,
  };
}
async function post(endpoint, body) {
  const t0 = Date.now();
  const r = await fetch(`${BASE}/api/render/${endpoint}`, {
    method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scenario: body }),
  });
  const buf = Buffer.from(await r.arrayBuffer());
  const text = buf.toString("utf8");
  let json = null;
  try { json = JSON.parse(text); } catch { /* binary or non-JSON */ }
  return { status: r.status, text, json, buf, bytes: buf.length, ms: Date.now() - t0 };
}
// An audit that retries through a refused scan (the phase-2 400).
async function auditWithRetry(body, tag) {
  let a = null;
  for (let i = 0; i <= RETRIES; i++) {
    a = await post("audit", body);
    if (a.status === 200) break;
    const refused = a.status === 400 && a.json?.detail?.error === CODE_SCAN;
    log(`${tag} attempt ${i + 1}: HTTP ${a.status}, ${a.ms} ms, ${refused ? "refused (" + a.json?.detail?.site_scan?.error + ")" : "unexpected: " + a.text.slice(0, 120)}`);
    if (!refused) break;
  }
  return a;
}
function pdfText(file) {
  const code = "import pypdfium2 as p,sys;d=p.PdfDocument(sys.argv[1]);print(' '.join(pg.get_textpage().get_text_bounded() for pg in d))";
  return execSync(`"${PY}" -c "${code}" "${file}"`, { env: { ...process.env, PYTHONUTF8: "1" } }).toString("utf8");
}
function ledgerLineOf(auditJsonPath) {
  const code = "import json,sys;from src.rendering.tier_ledger import tier_ledger,ledger_line;a=json.load(open(sys.argv[1],encoding='utf-8'));print(ledger_line(tier_ledger(a,None)))";
  return execSync(`"${PY}" -c "${code}" "${auditJsonPath}"`, { cwd: REPO, env: { ...process.env, PYTHONUTF8: "1" } }).toString("utf8").trim();
}
const detectedSet = (scan) => Object.entries(scan?.buckets ?? {}).filter(([, b]) => b?.detected === true).map(([k]) => k).sort().join(",");
const fired = (audit) => (audit?.sections?.site_adjustments ?? []).map((r) => r.flag).sort().join(",");
const pendingKinds = (audit) => (audit?.pending_verification?.items ?? []).map((i) => i.kind);
const corridorClean = (audit) => { const cv = audit?.sections?.corridor_validation ?? {}; return cv.checked === true && (cv.warnings ?? []).length === 0; };
// The breakdown row shape (render_api._format_breakdown_row): device, code, function, qty.
const labelsOf = (breakdown) => (breakdown?.devices ?? []).map((d) => `${d.code ?? ""} ${d.device ?? ""}`).join(" | ");
const note8 = (audit) => (audit?.sections?.colorado?.checks ?? []).find((c) => /both sides/i.test(c.label ?? ""));

async function runAxe(page, outName) {
  await page.evaluate(AXE_SRC);
  const res = await page.evaluate(() =>
    window.axe.run(document, { runOnly: { type: "tag", values: ["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"] } }),
  );
  const compact = res.violations.map((v) => ({ id: v.id, impact: v.impact, targets: v.nodes.map((n) => n.target.join(" ")) }));
  save(outName, JSON.stringify(compact, null, 2));
  return compact;
}
async function gotoSandbox(page) {
  for (let i = 0; i < 3; i++) {
    try {
      await page.goto(BASE + "/sandbox", { waitUntil: "networkidle", timeout: 60000 });
      await page.waitForTimeout(600);
      return;
    } catch (e) {
      if (i === 2) throw e;
      log("goto retry " + (i + 1) + ": " + String(e).slice(0, 80));
    }
  }
}
async function pinManually(page) {
  await page.getByRole("button", { name: "Enter manually", exact: true }).click();
  const fill = async (labelText, value) => {
    const input = page.locator(`label:text-is("${labelText}")`).locator("xpath=following-sibling::input[1]");
    await input.fill(value);
  };
  await fill("Latitude", LAT);
  await page.getByRole("button", { name: "Edit manually", exact: true }).click();
  await fill("Longitude", LNG);
  await fill("Bearing (° from N)", BEARING);
  await fill("Work zone (ft)", WORKLEN);
  await page.waitForTimeout(400);
}
const strip = (page) => page.evaluate(() => document.querySelector(".status-bar")?.textContent ?? "");
const hasRefusal = (page) => page.evaluate(() => !!document.querySelector(".sys-event.scan-refusal"));
const ledgerText = (page) => page.evaluate(() => document.querySelector('[data-testid="tier-ledger"]')?.textContent ?? "");
const blockText = (page) => page.evaluate(() => document.querySelector(".site-corrections")?.textContent ?? "");
const recordText = (page) => page.evaluate(() => Array.from(document.querySelectorAll(".site-correction")).map((n) => n.className + " :: " + (n.textContent ?? "")).join(" || "));
async function waitSettled(page, maxMs) {
  const t0 = Date.now();
  let settled = null;
  while (Date.now() - t0 < maxMs) {
    const s = await strip(page);
    if (/READY FOR TCS REVIEW|PLAN DECLINED|VERIFICATION UNAVAILABLE|NEEDS ATTENTION|VERIFIED/.test(s) && !/VERIFYING|COMPUTING/.test(s)) {
      settled = s; break;
    }
    await page.waitForTimeout(150);
  }
  return { settled, ms: Date.now() - t0 };
}
async function waitInFlightThenSettled(page, maxMs) {
  const t0 = Date.now();
  while (Date.now() - t0 < 5000) {
    const s = await strip(page);
    if (/VERIFYING|COMPUTING/.test(s)) break;
    await page.waitForTimeout(50);
  }
  return waitSettled(page, maxMs);
}
async function generateAndWait(page) {
  await page.getByRole("button", { name: /Generate plan/ }).click();
  return waitSettled(page, 90000);
}
async function openTiersAndRead(page) {
  const tiers = page.locator('[aria-label="Plan reference tiers"]');
  for (const label of ["Changed this plan", "Needs attention", "Checked & passed", "Pending / not verified", "Reference"]) {
    const sum = tiers.locator(".chip-sum", { hasText: label }).first();
    if ((await sum.count()) > 0 && (await sum.getAttribute("aria-expanded")) !== "true") {
      await sum.click();
      await page.waitForTimeout(150);
    }
  }
  return tiers.evaluate((el) => el.textContent ?? "");
}
// Retry a refused Generate in the browser (phase 2's refusal), up to RETRIES.
async function generateThroughRefusals(page) {
  let g = await generateAndWait(page);
  let cycles = 0;
  while ((await hasRefusal(page)) && cycles < RETRIES) {
    cycles++;
    log(`browser refusal seen — Retry scan (${cycles})`);
    await page.getByRole("button", { name: /Retry scan/ }).click();
    g = await waitInFlightThenSettled(page, 90000);
  }
  return { ...g, refused: await hasRefusal(page), cycles };
}

// ---- J ---- the pin-move leg, shared by the full run and ONLY_J.  The
// reachable pin-move affordance on /sandbox is the Location step's manual
// entry (GeneratorSidebar ManualFallback — the Latitude field writes
// meta.lat; since fix-224-manual-pin-move through withPin, THE door the
// picker's Save also uses).  After "Edit full setup" the manual panel may
// still be open from the pinning ("Hide manual entry"); otherwise "Edit
// manually" opens it.  Expects a correction on the wire at entry.
async function pinMoveLeg(page, requests) {
  let moved = false;
  try {
    await page.getByRole("button", { name: /Edit full setup/ }).click();
    await page.waitForTimeout(500);
    const openToggle = page.getByRole("button", { name: "Edit manually", exact: true });
    if ((await openToggle.count()) > 0) await openToggle.click();
    const latInput = page.locator('label:text-is("Latitude")').locator("xpath=following-sibling::input[1]");
    await latInput.waitFor({ timeout: 10000 });
    const before = requests.filter((r) => /audit$/.test(r.url)).pop();
    log(`J entry: the last audit request carried siteConditionOverrides ${JSON.stringify(before?.meta?.siteConditionOverrides ?? null)}`);
    await latInput.fill("39.711400");
    await page.waitForTimeout(400);
    const mark = requests.length;
    const gm = await generateThroughRefusals(page);
    const sentM = requests.slice(mark).filter((r) => /audit$/.test(r.url)).pop();
    moved = sentM?.meta?.lat !== undefined && Math.abs(Number(sentM.meta.lat) - 39.7114) < 1e-6;
    if (moved) ok(sentM.meta.siteConditionOverrides === undefined, "J1 after a pin move the next request carries no siteConditionOverrides (key dropped)", `${gm.ms} ms; meta.lat ${sentM.meta.lat}; siteConditionOverrides ${JSON.stringify(sentM.meta.siteConditionOverrides ?? null)}`);
    await page.screenshot({ path: path.join(OUT, "J-after-pin-move.png"), fullPage: true });
  } catch (err) { log("J: " + String(err).slice(0, 160)); }
  if (!moved) note("J1 the pin-move affordance was not reachable this way in the browser; the clearing is pinned on withPin (GeneratorSidebar.manual-pin-move.test, GeneratorShell.picker-reapply.test)");
}

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  log(`# s2a18 live check — ${PROD ? "PRODUCTION" : "LOCAL"}`);
  log(`UTC: ${new Date().toISOString()}`);
  log(`BASE: ${BASE}`);
  const h = await fetch(HEALTHZ);
  const hz = await h.text();
  log(`healthz (HTTP ${h.status}): ${hz}`);
  if (PROD) {
    const sha = (() => { try { return JSON.parse(hz).sha; } catch { return null; } })();
    const om = execSync("git rev-parse origin/main").toString().trim();
    log(`git rev-parse origin/main: ${om}`);
    if (!ok(sha === om, "GATE — healthz sha == origin/main", `${sha} vs ${om}`)) {
      log("GATE FAILED — aborting; nothing below was run.");
      finish(2);
    }
  } else {
    const head = execSync("git rev-parse HEAD").toString().trim();
    log(`git rev-parse HEAD: ${head} — local mode: the served build is this working tree (next dev + uvicorn at ${HEALTHZ}), not a deploy.`);
  }
  log("");

  if (ONLY_J) {
    log("ONLY_J: the gate, then browser pin → Generate → Assert → J → axe. Legs A–I and L not run.");
    const browser = await chromium.launch();
    try {
      const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
      const requests = [];
      const audits = [];
      page.on("request", (req) => {
        const u = req.url();
        if (/\/api\/render\/(audit|device-breakdown)$/.test(u) && req.method() === "POST") {
          let scen = null;
          try { scen = JSON.parse(req.postData() || "{}").scenario; } catch { /* ignore */ }
          requests.push({ url: u.replace(BASE, ""), meta: scen?.meta ?? null, site_scan: scen?.site_scan ?? null, t: Date.now() });
        }
      });
      page.on("response", async (res) => {
        if (/\/api\/render\/audit$/.test(res.url()) && res.request().method() === "POST") {
          try { audits.push({ status: res.status(), json: await res.json(), t: Date.now() }); } catch { /* not json */ }
        }
      });
      await gotoSandbox(page);
      await pinManually(page);
      await waitSettled(page, 60000);
      const gen = await generateThroughRefusals(page);
      ok(gen.settled !== null && !gen.refused, "J0 Generate at Lakewood settles with an ok scan", `${gen.ms} ms — ${gen.settled?.slice(0, 70)}`);
      const served0 = audits.filter((x) => x.status === 200 && x.json?.sections?.site_scan?.status === "ok").pop();
      const schoolAbsent = served0 && served0.json.sections.site_scan.buckets?.schools && served0.json.sections.site_scan.buckets.schools.detected !== true;
      if (schoolAbsent) {
        const row = page.locator(".site-correction-row", { hasText: "School zone" }).first();
        const mark = requests.length;
        await row.getByRole("button", { name: "Assert" }).click();
        const ga = await waitInFlightThenSettled(page, 90000);
        const sentA = requests.slice(mark).filter((r) => /audit$/.test(r.url)).pop();
        ok(sentA?.meta?.siteConditionOverrides?.[0]?.action === "assert", "J0 Assert puts a correction on the wire (the precondition)", `${ga.ms} ms; ${JSON.stringify(sentA?.meta?.siteConditionOverrides ?? null)}`);
        await pinMoveLeg(page, requests);
        const axe = await runAxe(page, "axe-after-pin-move.json");
        ok(axe.length <= AXE_BASELINE, `K axe after the pin move: ${axe.length} violation(s) ≤ baseline ${AXE_BASELINE}`, axe.map((x) => `${x.id} ${x.targets.join(",").slice(0, 60)}`).join("; ") || "none");
      } else ok(false, "J0 the browser's scan left no absent School zone row to assert on", `${audits.length} audit responses`);
      await page.close();
    } finally {
      await browser.close();
    }
    log("");
    log(`RESULT: ${fail === 0 ? "ALL PASS" : "FAILURES"} ${pass}/${pass + fail} (+${info} INFO)`);
    finish(fail === 0 ? 0 : 1);
  }

  // ---- A ---- baseline
  const a = await auditWithRetry(scenario(), "A");
  save("A-baseline-audit.json", a.text);
  const aScan = a.json?.sections?.site_scan;
  const aOk = a.status === 200 && aScan?.status === "ok";
  ok(aOk, "A1 baseline scanned audit answers ok", `HTTP ${a.status}, ${a.ms} ms, status=${aScan?.status}, detected: ${detectedSet(aScan) || "none"}`);
  if (!aOk) {
    note("A the scan never answered ok — every correction leg needs an ok scan; proven at test level (tests/test_site_scan_corrections.py through the real routes)");
    finish(fail === 0 ? 0 : 1);
  }
  const aSidewalk = aScan.buckets?.sidewalks?.detected === true;
  ok(aSidewalk && aScan.flags?.pedestrian_facility === true && fired(a.json).includes("pedestrian_facility"),
    "A2 the baseline detects sidewalks and fires the sidewalk adjustment", `flags ${JSON.stringify(aScan.flags)}; fired ${fired(a.json)}`);
  ok((aScan.corrections ?? []).length === 0 && !pendingKinds(a.json).includes("site_condition_overridden"),
    "A3 no corrections on the wire ⇒ none disclosed, no pending item", `pending kinds ${JSON.stringify(pendingKinds(a.json))}`);
  const abd = await post("device-breakdown", scenario());
  save("A-baseline-breakdown.json", abd.text);
  const aHasR99 = /R9-9/.test(labelsOf(abd.json));
  ok(abd.status === 200 && aHasR99, "A4 the baseline device list carries R9-9 SIDEWALK CLOSED", `HTTP ${abd.status}, R9-9 ${aHasR99}`);
  const aPending = a.json.pending_verification?.count ?? 0;
  const aN8 = note8(a.json);
  if (aN8) note(`A #243 boundary — the Note 8 check reads pass=${aN8.pass} on the baseline (divided road): "${aN8.detail}"`);

  // ---- B ---- dismiss
  const b = await auditWithRetry(scenario({}, [DISMISS_SIDEWALK]), "B");
  save("B-dismissed-audit.json", b.text);
  const bScan = b.json?.sections?.site_scan;
  const bOk = b.status === 200 && bScan?.status === "ok";
  ok(bOk, "B1 the dismissed audit answers ok", `HTTP ${b.status}, ${b.ms} ms`);
  let bSentence = null;
  if (bOk) {
    const [c] = bScan.corrections ?? [];
    bSentence = c?.disclosure ?? null;
    ok(c && c.status === "applied" && c.action === "dismiss" && c.scan_detected === true && typeof c.disclosure === "string" && /dismissed the scan's pedestrian sidewalks: fenced off/.test(c.disclosure),
      "B2 the correction is applied with the scan's verdict and ONE backend sentence", c ? `${c.status}, scan_detected ${c.scan_detected}: "${c.disclosure}"` : "no correction on the wire");
    ok(bScan.flags?.pedestrian_facility === undefined && !fired(b.json).includes("pedestrian_facility") && bScan.buckets?.sidewalks?.detected === true,
      "B3 pedestrian_facility leaves the flags and its record no longer fires while the scan still says detected", `flags ${JSON.stringify(bScan.flags)}; fired ${fired(b.json)}`);
    const items = (b.json.pending_verification?.items ?? []).filter((i) => i.kind === "site_condition_overridden");
    ok(items.length === 1 && items[0].label === bSentence && /issues\/224$/.test(items[0].tracking_issue ?? ""),
      "B4 ONE pending item carries the sentence verbatim (the #177 shape)", `${items.length} item(s); pending ${aPending} → ${b.json.pending_verification?.count}`);
    ok((b.json.pending_verification?.count ?? 0) === aPending + 1, "B5 pending = baseline + 1", `${aPending} → ${b.json.pending_verification?.count}`);
    ok(b.json.plan_flags?.is_clean === false, "B6 is_clean is false with an operator override pending");
    const bbd = await post("device-breakdown", scenario({}, [DISMISS_SIDEWALK]));
    save("B-dismissed-breakdown.json", bbd.text);
    ok(bbd.status === 200 && !/R9-9/.test(labelsOf(bbd.json)), "B7 the dismissed plan's device list has no R9-9 — the backend re-generated", `HTTP ${bbd.status}`);
  }

  // ---- C ---- assert
  const c = await auditWithRetry(scenario({}, [ASSERT_SCHOOL]), "C");
  save("C-asserted-audit.json", c.text);
  const cScan = c.json?.sections?.site_scan;
  const cOk = c.status === 200 && cScan?.status === "ok";
  ok(cOk, "C1 the asserted audit answers ok", `HTTP ${c.status}, ${c.ms} ms`);
  if (cOk) {
    const [cc] = cScan.corrections ?? [];
    ok(cc && cc.status === "applied" && cc.action === "assert" && cc.scan_detected === false && /asserted school zone — the scan found none/.test(cc.disclosure ?? ""),
      "C2 the assert is applied with the scan's verdict (none) and the backend sentence", cc ? `"${cc.disclosure}"` : "no correction");
    ok(cScan.flags?.school_zone === true && fired(c.json).includes("school_zone"), "C3 school_zone joins the flags and its record fires", `fired ${fired(c.json)}`);
    ok((c.json.pending_verification?.count ?? 0) === aPending + 1, "C4 pending = baseline + 1", `${aPending} → ${c.json.pending_verification?.count}`);
    const cbd = await post("device-breakdown", scenario({}, [ASSERT_SCHOOL]));
    save("C-asserted-breakdown.json", cbd.text);
    ok(cbd.status === 200 && /S1-1/.test(labelsOf(cbd.json)), "C5 the asserted plan's device list carries S1-1 SCHOOL", `HTTP ${cbd.status}`);
    const cN8 = note8(c.json);
    if (cN8) note(`C #243 boundary — Note 8 on the asserted plan reads pass=${cN8.pass}: "${cN8.detail}" (expected on this divided road; not this arc's defect)`);
  }

  // ---- D ---- moot
  const d = await auditWithRetry(scenario({}, [ASSERT_SIDEWALK]), "D");
  save("D-moot-audit.json", d.text);
  const dScan = d.json?.sections?.site_scan;
  if (d.status === 200 && dScan?.status === "ok") {
    const [dc] = dScan.corrections ?? [];
    ok(dc && dc.status === "moot" && /assertion of pedestrian sidewalks is moot/.test(dc.disclosure ?? ""), "D1 asserting the detected sidewalk is moot — disclosed, never dropped", dc ? `"${dc.disclosure}"` : "no correction");
    ok(fired(d.json) === fired(a.json) && !pendingKinds(d.json).includes("site_condition_overridden"), "D2 a moot correction changes nothing: records as the baseline, no pending item", `fired ${fired(d.json)}`);
  } else ok(false, "D1 the moot audit answers ok", `HTTP ${d.status}`);

  // ---- E ---- the honest 400
  const e = await post("audit", scenario({}, [{ flag: "pedestrian_facility", action: "dismiss", recorded_at: AT }]));
  save("E-bad-override.json", e.text);
  ok(e.status === 400 && e.json?.detail?.error === CODE_OVERRIDE && /needs a reason/.test(e.json?.detail?.message ?? "") && e.json?.detail?.recovery?.field === "meta.siteConditionOverrides",
    "E1 a dismiss without a reason is the honest 400 with the code and the recovery field", `HTTP ${e.status}: ${e.json?.detail?.message ?? e.text.slice(0, 120)}`);

  // ---- F ---- audit PDF over the dismissed plan
  const fpdf = await post("audit-pdf", scenario({}, [DISMISS_SIDEWALK]));
  ok(fpdf.status === 200 && fpdf.bytes > 1000, "F1 the dismissed plan's audit PDF renders", `HTTP ${fpdf.status}, ${fpdf.bytes} B, ${fpdf.ms} ms`);
  if (fpdf.status === 200 && bOk) {
    save("F-dismissed-audit.pdf", fpdf.buf);
    let text = "";
    try { text = pdfText(path.join(OUT, "F-dismissed-audit.pdf")); } catch (err) { log("pdf text extraction failed: " + String(err).slice(0, 120)); }
    ok(/dismissed/.test(text) && /Operator corrections to the site scan/.test(text), "F2 the Site Conditions table's Result cell names the dismissal and the body carries the lead", `dismissed ${/dismissed/.test(text)}, lead ${/Operator corrections to the site scan/.test(text)}`);
    const cover = (text.match(/Plan status\s+([^\r\n]*?reference)/) || [])[1] ?? "";
    const wantLine = ledgerLineOf(path.join(OUT, "B-dismissed-audit.json"));
    const pdfDetected = ["Adjacent at-grade", "Adjacent interchange", "Pedestrian sidewalks", "Bike lane", "School zone"].filter((l) => new RegExp(l + "[^\\n]{0,80}DETECTED").test(text)).length;
    const bDetected = detectedSet(bScan).split(",").filter(Boolean).length;
    const pdfClean = /corridor check ran with no warnings/.test(text);
    if (pdfDetected === bDetected && pdfClean === corridorClean(b.json)) ok(cover === wantLine, "F3 the audit-PDF cover line equals the classifier line over the served dismissed audit", `cover "${cover}" vs served "${wantLine}"`);
    else note("F3 the PDF's own request differs from leg B's in a per-request fact (detected set or corridor outcome), so the two are different classifier inputs; parity on ONE audit is pinned at test level (test_audit_blocks_site_scan real-PDF cases)", `pdf detected ${pdfDetected} vs B ${bDetected}; pdf corridor clean ${pdfClean} vs B ${corridorClean(b.json)}; cover "${cover}"`);
  }

  // ---- G ---- sheet + narrative over the dismissed plan
  const gpdf = await post("pdf", scenario({}, [DISMISS_SIDEWALK]));
  const gmd = await post("markdown", scenario({}, [DISMISS_SIDEWALK]));
  ok(gpdf.status === 200 && gmd.status === 200, "G1 the dismissed plan's sheet + narrative render (200)", `sheet HTTP ${gpdf.status} ${gpdf.ms} ms · md HTTP ${gmd.status} ${gmd.ms} ms`);
  if (gpdf.status === 200 && gmd.status === 200) {
    save("G-dismissed-sheet.pdf", gpdf.buf);
    save("G-dismissed-narrative.md", gmd.text);
    let sheet = "";
    try { sheet = pdfText(path.join(OUT, "G-dismissed-sheet.pdf")); } catch (err) { log("pdf text extraction failed: " + String(err).slice(0, 120)); }
    ok(/CORRECTED BY OPERATOR/.test(sheet) && /pedestrian sidewalks dismissed \(fenced off\)/.test(sheet) && /DRAFT FOR PE REVIEW/.test(sheet),
      "G2 the sheet's notes box carries the CORRECTED BY OPERATOR line before the DRAFT trailer");
    ok(gmd.text.includes("## Site Conditions") && (bSentence ? gmd.text.includes(bSentence) : /Operator dismissed/.test(gmd.text)),
      "G3 the narrative's ## Site Conditions block carries the sentence verbatim");
  }

  // ---- H / I / J / K — browser ----
  const browser = await chromium.launch();
  const axeCounts = {};
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const requests = [];
    const audits = [];
    page.on("request", (req) => {
      const u = req.url();
      if (/\/api\/render\/(audit|device-breakdown)$/.test(u) && req.method() === "POST") {
        let scen = null;
        try { scen = JSON.parse(req.postData() || "{}").scenario; } catch { /* ignore */ }
        requests.push({ url: u.replace(BASE, ""), meta: scen?.meta ?? null, site_scan: scen?.site_scan ?? null, t: Date.now() });
      }
    });
    page.on("response", async (res) => {
      if (/\/api\/render\/audit$/.test(res.url()) && res.request().method() === "POST") {
        try { audits.push({ status: res.status(), json: await res.json(), t: Date.now() }); } catch { /* not json */ }
      }
    });
    await gotoSandbox(page);
    await pinManually(page);
    await waitSettled(page, 60000);
    const gen = await generateThroughRefusals(page);
    ok(gen.settled !== null && !gen.refused, "H1 Generate at Lakewood settles with an ok scan", `${gen.ms} ms — ${gen.settled?.slice(0, 70)}${gen.cycles ? ` (after ${gen.cycles} retry)` : ""}`);
    await page.screenshot({ path: path.join(OUT, "H-post-generate.png"), fullPage: true });
    const served0 = audits.filter((x) => x.status === 200 && x.json?.sections?.site_scan?.status === "ok").pop();
    if (!served0 || gen.refused) {
      ok(false, "H2 an ok scanned audit was captured from the browser's own fetches", `${audits.length} audit responses; refused ${gen.refused}`);
    } else {
      save("H-served-audit-0.json", JSON.stringify(served0.json));
      const line0 = ledgerLineOf(path.join(OUT, "H-served-audit-0.json"));
      ok((await ledgerText(page)).includes(line0), "H2 pre-correction: the on-screen ledger equals the classifier over the served audit", line0);
      const block0 = await blockText(page);
      ok(/Site conditions — scanned/.test(block0) && /Pedestrian sidewalks/.test(block0) && /a correction re-generates the plan/.test(block0),
        "H3 the strip shows \"Site conditions — scanned\" with the sidewalk row", block0.slice(0, 160));
      const sidewalkDetected = served0.json.sections.site_scan.buckets?.sidewalks?.detected === true;
      const metaBefore = JSON.stringify(requests.filter((r) => /audit$/.test(r.url)).pop()?.meta ?? null);
      if (sidewalkDetected) {
        const row = page.locator(".site-correction-row", { hasText: "Pedestrian sidewalks" }).first();
        await row.getByRole("button", { name: "Dismiss" }).click();
        await page.waitForTimeout(200);
        const confirmBtn = page.getByRole("button", { name: "Confirm dismiss" });
        ok(await confirmBtn.isDisabled(), "H4 the confirm stays disabled until a reason is chosen");
        await page.getByLabel(/Reason for dismissing Pedestrian sidewalks/).selectOption("fenced");
        const mark = requests.length;
        await confirmBtn.click();
        const gd = await waitInFlightThenSettled(page, 90000);
        const sent = requests.slice(mark).filter((r) => /audit$/.test(r.url)).pop();
        ok(sent?.meta?.siteConditionOverrides?.length === 1 && sent.meta.siteConditionOverrides[0].flag === "pedestrian_facility" && sent.meta.siteConditionOverrides[0].reason === "fenced",
          "H5 the next audit request carries the dismiss marker (reason fenced)", JSON.stringify(sent?.meta?.siteConditionOverrides ?? null));
        ok(gd.settled !== null, "H6 the plan re-generates and settles", `${gd.ms} ms — ${gd.settled?.slice(0, 70)}`);
        await page.screenshot({ path: path.join(OUT, "H-dismissed.png"), fullPage: true });
        const served1 = audits.filter((x) => x.status === 200 && (x.json?.sections?.site_scan?.corrections ?? []).length === 1).pop();
        if (served1) {
          save("H-served-audit-dismissed.json", JSON.stringify(served1.json));
          const line1 = ledgerLineOf(path.join(OUT, "H-served-audit-dismissed.json"));
          const shown1 = await ledgerText(page);
          ok(shown1.includes(line1), "H7 the on-screen ledger equals the classifier over the browser's own served corrected audit", `screen "${shown1.trim()}" vs classifier "${line1}"`);
          const sentence = served1.json.sections.site_scan.corrections[0].disclosure;
          const rec = await recordText(page);
          ok(/dismissed/.test(rec) && rec.includes(sentence) && /×/.test(rec), "H8 the row is the × record with the backend sentence and Undo", rec.slice(0, 200));
          const tiers = await openTiersAndRead(page);
          ok(/dismissed by operator/.test(tiers) && tiers.includes(sentence), "H9 section 03 shows the dismissed ✓ row with the sentence");
          ok((served1.json.pending_verification?.count ?? 0) === (served0.json.pending_verification?.count ?? 0) + 1, "H10 pending = pre-correction + 1 on the browser's own audits", `${served0.json.pending_verification?.count} → ${served1.json.pending_verification?.count}`);
          await page.screenshot({ path: path.join(OUT, "H-section03-open.png"), fullPage: true });
          axeCounts.dismissed = await runAxe(page, "axe-dismissed.json");
          // Undo
          const mark2 = requests.length;
          await page.locator(".site-correction").first().getByRole("button", { name: "Undo" }).click();
          const gu = await waitInFlightThenSettled(page, 90000);
          const sentU = requests.slice(mark2).filter((r) => /audit$/.test(r.url)).pop();
          ok(JSON.stringify(sentU?.meta ?? null) === metaBefore, "H11 after Undo the next request's meta is byte-identical to the pre-dismiss request's meta", `${gu.ms} ms`);
          const shownU = await ledgerText(page);
          ok(shownU.includes(line0), "H12 the ledger returns to its pre-dismiss line", `screen "${shownU.trim()}" vs "${line0}"`);
        } else ok(false, "H7 no corrected audit was captured from the browser");
      } else note("H4–H12 the browser's scan did not detect sidewalks this run, so there was nothing to dismiss; the dismiss flow is pinned mounted (SetupStrip.corrections.test) and on the wire in leg B");

      // ---- I ---- assert
      const schoolAbsent = served0.json.sections.site_scan.buckets?.schools && served0.json.sections.site_scan.buckets.schools.detected !== true;
      if (schoolAbsent) {
        const row = page.locator(".site-correction-row", { hasText: "School zone" }).first();
        const mark3 = requests.length;
        await row.getByRole("button", { name: "Assert" }).click();
        const ga = await waitInFlightThenSettled(page, 90000);
        const sentA = requests.slice(mark3).filter((r) => /audit$/.test(r.url)).pop();
        ok(sentA?.meta?.siteConditionOverrides?.[0]?.action === "assert" && sentA.meta.siteConditionOverrides[0].flag === "school_zone", "I1 Assert writes the assert marker and re-generates", `${ga.ms} ms; ${JSON.stringify(sentA?.meta?.siteConditionOverrides ?? null)}`);
        const servedA = audits.filter((x) => x.status === 200 && (x.json?.sections?.site_scan?.corrections ?? []).some((cc) => cc.action === "assert")).pop();
        if (servedA) {
          save("I-served-audit-asserted.json", JSON.stringify(servedA.json));
          const rec = await recordText(page);
          const sentence = servedA.json.sections.site_scan.corrections.find((cc) => cc.action === "assert").disclosure;
          ok(/confirmed/.test(rec) && rec.includes(sentence), "I2 the row is the ✓ record with the backend sentence", rec.slice(0, 200));
          const tiers = await openTiersAndRead(page);
          ok(/School zone nearby/.test(tiers) && tiers.includes(sentence) && /OPERATOR/.test(tiers), "I3 section 03's changed row carries the sentence, tag OPERATOR");
          const n8 = note8(servedA.json);
          if (n8) note(`I #243 boundary — Note 8 reads pass=${n8.pass} with the asserted school zone: "${n8.detail}" (expected on this divided road; not this arc's defect)`);
          await page.screenshot({ path: path.join(OUT, "I-asserted.png"), fullPage: true });
          axeCounts.asserted = await runAxe(page, "axe-asserted.json");
          // ---- J ---- pin move clears the corrections
          await pinMoveLeg(page, requests);
        } else ok(false, "I2 no asserted audit was captured from the browser");
      } else note("I the browser's scan reported a school zone or no schools bucket this run; the assert flow is on the wire in leg C and pinned mounted");
      if (!axeCounts.dismissed && !axeCounts.asserted) axeCounts.post = await runAxe(page, "axe-post-generate.json");
    }
    await page.close();
  } finally {
    await browser.close();
  }

  // ---- K ----
  for (const [state, v] of Object.entries(axeCounts)) {
    ok(v.length <= AXE_BASELINE, `K axe ${state}: ${v.length} violation(s) ≤ baseline ${AXE_BASELINE}`, v.map((x) => `${x.id} ${x.targets.join(",").slice(0, 60)}`).join("; ") || "none");
  }

  // ---- L ----
  note("L saved-plan reload carries the corrections — proven at test level (GeneratorShell.picker-reapply seeds meta.siteConditionOverrides through initialScenario, the saved-plan path); the sandbox has no save");
  log(`SIZE — baseline audit ${a.bytes} B; dismissed audit ${b.bytes} B; dismissed audit PDF ${fpdf.bytes} B`);
  log("");
  log(`RESULT: ${fail === 0 ? "ALL PASS" : "FAILURES"} ${pass}/${pass + fail} (+${info} INFO)`);
  finish(fail === 0 ? 0 : 1);
})().catch((e) => {
  log("SCRIPT ERROR: " + String(e && e.stack ? e.stack : e));
  finish(3);
});
